# Generated by Django 2.2.3 on 2019-07-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exam', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=45)),
                ('board', models.CharField(max_length=45)),
                ('passing_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=45)),
                ('trainer', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bcs', 'BCS'), ('nationalized', 'Nationalized'), ('10% quota', '10% quota'), ('non govt.', 'Non Govt.')], max_length=45)),
                ('joning_date', models.DateField()),
                ('institute_name', models.CharField(max_length=100)),
                ('scale', models.IntegerField()),
                ('grade_of_post', models.CharField(max_length=45)),
                ('first_time_scale_due_year', models.IntegerField()),
                ('second_time_scale_due_year', models.IntegerField()),
                ('promotion_due_year', models.IntegerField()),
                ('recreation_leave_due_year', models.IntegerField()),
                ('expected_retirement_year', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department')),
                ('job_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.District')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('upazilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Upazilla')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality', models.CharField(max_length=45)),
                ('religion', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5)),
                ('e_tin', models.IntegerField(unique=True)),
                ('nid', models.IntegerField(unique=True)),
                ('driving_license_passport', models.IntegerField(unique=True)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('father_name', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('single', 'Single')], max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AddressInfo')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.EducationInfo')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.ExperienceInfo')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.JobInfo')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TrainingInfo')),
            ],
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.District'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Union'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='upazilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Upazilla'),
        ),
    ]
