# Generated by Django 2.2.3 on 2019-07-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.District'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Union'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='upazilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Upazilla'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.AddressInfo'),
        ),
    ]
