# Generated by Django 2.2.3 on 2019-07-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190712_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.EducationInfo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.ExperienceInfo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.JobInfo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.TrainingInfo'),
        ),
    ]
