# Generated by Django 2.2.3 on 2019-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_classinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='display_name',
            field=models.CharField(default='i', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
