# Generated by Django 2.2.3 on 2019-07-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20190714_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
