# Generated by Django 2.2.3 on 2019-07-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20190714_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='upazilla',
        ),
        migrations.RemoveField(
            model_name='upazilla',
            name='district',
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.District'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Union'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='upazilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Upazilla'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Union',
        ),
        migrations.DeleteModel(
            name='Upazilla',
        ),
    ]
