# Generated by Django 2.2.3 on 2019-07-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20190715_1208'),
        ('teacher', '0012_auto_20190715_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Department')),
                ('guide_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.GuideTeacher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Session')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Shift')),
            ],
        ),
    ]
