# Generated by Django 2.2.3 on 2019-07-15 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_classregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideteacher',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
