# Generated by Django 2.2.3 on 2019-07-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_guideteacher_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregistration',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo'),
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Department'),
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='guide_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.GuideTeacher'),
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Section'),
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Session'),
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Shift'),
        ),
        migrations.AlterField(
            model_name='guideteacher',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PersonalInfo'),
        ),
    ]
