# Generated by Django 2.2.3 on 2019-07-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20190715_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideteacher',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PersonalInfo', unique=True),
        ),
    ]
