# Generated by Django 2.2.3 on 2019-07-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20190715_1208'),
        ('teacher', '0016_auto_20190715_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideteacher',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PersonalInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='classregistration',
            unique_together={('class_name', 'section', 'shift', 'guide_teacher')},
        ),
    ]
