# Generated by Django 2.2.3 on 2019-08-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_auto_20190716_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideteacher',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PersonalInfo'),
        ),
    ]
