# Generated by Django 3.0.2 on 2020-01-12 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_auto_20190807_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
