# Generated by Django 3.0.2 on 2020-01-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0006_auto_20200115_1205'),
        ('student', '0020_auto_20200115_1205'),
        ('teacher', '0021_auto_20200115_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRegistration',
        ),
    ]
