# Generated by Django 3.0.2 on 2020-01-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20200117_1510'),
        ('teacher', '0022_delete_classregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuideTeacher',
        ),
    ]
