# Generated by Django 3.0.2 on 2020-01-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_auto_20200115_0748'),
        ('student', '0019_auto_20200115_0748'),
        ('employee', '0002_auto_20200115_0748'),
        ('administration', '0002_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='upazilla',
        ),
        migrations.RemoveField(
            model_name='upazilla',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Union',
        ),
        migrations.DeleteModel(
            name='Upazilla',
        ),
    ]
