# Generated by Django 3.1 on 2020-12-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_guardianinfo_login_details'),
        ('academic', '0002_auto_20201123_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=102)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=102)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('amount', models.FloatField()),
                ('classes', models.ManyToManyField(to='academic.ClassRegistration')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeesPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.academicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ManyToManyField(blank=True, to='fees.Discount')),
                ('fees', models.ManyToManyField(to='fees.Fees')),
                ('paid', models.ManyToManyField(to='fees.StudentFeesPaid')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.academicinfo')),
            ],
        ),
    ]
