# Generated by Django 3.1 on 2020-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20201211_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfees',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='studentfeespaid',
            name='fee_type',
        ),
        migrations.AddField(
            model_name='fees',
            name='paid',
            field=models.ManyToManyField(blank=True, to='fees.StudentFeesPaid'),
        ),
    ]
