# Generated by Django 3.1 on 2020-12-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20201212_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='paid',
        ),
        migrations.AddField(
            model_name='studentfees',
            name='paid',
            field=models.ManyToManyField(blank=True, to='fees.StudentFeesPaid'),
        ),
        migrations.AddField(
            model_name='studentfeespaid',
            name='fee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fees.fees'),
        ),
    ]
