# Generated by Django 3.1 on 2020-12-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20201212_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='fee_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='fees.fees'),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='total_owed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
    ]
