# Generated by Django 3.1 on 2020-12-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_auto_20201213_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='fee_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='fees.fees'),
        ),
        migrations.AlterField(
            model_name='studentfeespaid',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.fees'),
        ),
    ]
