# Generated by Django 3.1 on 2020-12-16 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_auto_20201215_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
