# Generated by Django 3.1 on 2020-11-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classregistration',
            name='guide_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AlterUniqueTogether(
            name='classregistration',
            unique_together={('class_name', 'name')},
        ),
    ]
