# Generated by Django 2.2.3 on 2019-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20190715_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
