# Generated by Django 3.0.2 on 2020-01-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_auto_20200115_0748'),
        ('academic', '0003_auto_20190715_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('general', 'General'), ('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities')], max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo')),
                ('guide_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.GuideTeacher')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Section')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Session')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Shift')),
            ],
            options={
                'unique_together': {('class_name', 'section', 'shift', 'guide_teacher')},
            },
        ),
    ]
