# Generated by Django 3.1 on 2020-11-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField(choices=[(0, 'All'), (1, 'Playgroup'), (2, 'Pre-nursery'), (3, 'Nursery 1'), (4, 'Nursery 2'), (5, 'Reception Year'), (6, 'Primary 1'), (7, 'Primary 2'), (8, 'Primary 3'), (9, 'Primary 4'), (10, 'Primary 5'), (11, 'JSS 1'), (12, 'JSS 2'), (13, 'JSS 3'), (14, 'SS 1'), (15, 'SS 2'), (16, 'SS 3')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.classitems')),
                ('students_given', models.ManyToManyField(blank=True, to='student.EnrolledStudent')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('location', models.CharField(blank=True, help_text='Store, Admin Office', max_length=45, null=True)),
                ('expiry_years', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.CharField(max_length=60)),
                ('issue_date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=1)),
                ('return_date', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
                ('comment', models.CharField(default='null', max_length=65)),
                ('damaged', models.BooleanField(default=False)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='classitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
