# Generated by Django 3.1 on 2020-11-25 01:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentitems',
            name='date_given',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 11, 25)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.classitems'),
        ),
        migrations.RemoveField(
            model_name='studentitems',
            name='students_given',
        ),
        migrations.AddField(
            model_name='studentitems',
            name='students_given',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='student.enrolledstudent'),
        ),
    ]
