# Generated by Django 3.1 on 2020-11-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
            ],
            options={
                'unique_together': {('section', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('no_of_times_a_week', models.IntegerField()),
                ('is_before_short_break', models.BooleanField(default=False)),
                ('is_before_long_break', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.IntegerField()),
                ('max_periods_a_week', models.IntegerField()),
                ('unavailable_days', models.ManyToManyField(blank=True, to='timetable.Days')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.period')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classregistration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.sectionsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='additional_teacher',
            field=models.ManyToManyField(blank=True, null=True, to='timetable.Teacher'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject_teacher', to='timetable.teacher'),
        ),
        migrations.CreateModel(
            name='Class_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField(choices=[(1, 'Playgroup'), (2, 'Pre-nursery'), (3, 'Nursery 1'), (4, 'Nursery 2'), (5, 'Reception Year'), (6, 'Primary 1'), (7, 'Primary 2'), (8, 'Primary 3'), (9, 'Primary 4'), (10, 'Primary 5'), (11, 'JSS 1'), (12, 'JSS 2'), (13, 'JSS 3'), (14, 'SS 1'), (15, 'SS 2'), (16, 'SS 3')], null=True, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('subjects', models.ManyToManyField(to='timetable.SectionSubject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sectionsubject',
            unique_together={('teacher', 'name', 'section')},
        ),
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('Short Break', 'Short Break'), ('Long Break', 'Long Break'), ('Other', 'Other')], max_length=18)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
            ],
            options={
                'unique_together': {('break_type', 'section')},
            },
        ),
    ]
