# Generated by Django 3.1 on 2020-10-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '__first__'),
        ('academic', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=10)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'unique_together': {('section', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.period')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classregistration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='result.subjectregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('Short Break', 'Short Break'), ('Long Break', 'Long Break'), ('Other', 'Other')], max_length=18)),
                ('section', models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=18)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'unique_together': {('break_type', 'section')},
            },
        ),
    ]
