# Generated by Django 3.1 on 2020-12-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsubject',
            name='additional_teacher',
            field=models.ManyToManyField(blank=True, to='timetable.Teacher'),
        ),
    ]
