# Generated by Django 3.1 on 2020-11-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_guardian_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('relationship_with_student', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt')], max_length=45)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone_no', models.CharField(max_length=11)),
                ('father_occupation', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone_no', models.CharField(max_length=11)),
                ('mother_occupation', models.CharField(max_length=45)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone_no', models.CharField(max_length=11)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship_with_student', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='student-photos/')),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('religion', models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Others', 'Others')], max_length=45)),
                ('address', models.CharField(default='default', max_length=109)),
                ('nationality', models.CharField(choices=[('Nigerian', 'Nigerian'), ('Others', 'Others')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousAcademicCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('release_letter', models.FileField(blank=True, upload_to='documents/')),
                ('testimonial', models.FileField(blank=True, upload_to='documents/')),
                ('marksheet', models.FileField(blank=True, upload_to='documents/')),
                ('stipen_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('other_certificate', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousAcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('former_school_name', models.CharField(max_length=100)),
                ('school_location', models.CharField(max_length=100)),
                ('school_phone_no', models.IntegerField()),
                ('exit_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField(choices=[(1, 'Playgroup'), (2, 'Pre-nursery'), (3, 'Nursery 1'), (4, 'Nursery 2'), (5, 'Reception Year'), (6, 'Primary 1'), (7, 'Primary 2'), (8, 'Primary 3'), (9, 'Primary 4'), (10, 'Primary 5'), (11, 'JSS 1'), (12, 'JSS 2'), (13, 'JSS 3'), (14, 'SS 1'), (15, 'SS 2'), (16, 'SS 3')])),
                ('registration_no', models.IntegerField(default=student.models.random_int, unique=True)),
                ('status', models.CharField(choices=[('not enroll', 'Not Enroll'), ('enrolled', 'Enrolled'), ('regular', 'Regular'), ('irregular', 'Irregular'), ('passed', 'Passed')], default='not enroll', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('emergency_contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.emergencycontactdetails')),
                ('guardian_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.guardianinfo')),
                ('login_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.personalinfo')),
                ('previous_academic_certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.previousacademiccertificate')),
                ('previous_academic_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.previousacademicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classregistration')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.academicinfo')),
            ],
            options={
                'unique_together': {('class_name', 'roll')},
            },
        ),
    ]
