# Generated by Django 2.2.3 on 2019-07-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190720_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicinfo',
            old_name='previoud_academic_certificate',
            new_name='previous_academic_certificate',
        ),
        migrations.RenameField(
            model_name='academicinfo',
            old_name='previoud_academic_info',
            new_name='previous_academic_info',
        ),
    ]
