# Generated by Django 2.2.3 on 2019-08-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190804_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='address_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentAddressInfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.ClassRegistration'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='emergency_contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.EmergencyContactDetails'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='guardian_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.GuardianInfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='previous_academic_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PreviousAcademicCertificate'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='previous_academic_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PreviousAcademicInfo'),
        ),
    ]
