# Generated by Django 3.0.2 on 2020-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200130_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=634493, unique=True),
        ),
    ]
