# Generated by Django 2.2.3 on 2019-08-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190807_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='address_info',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='student.StudentAddressInfo'),
        ),
    ]
