# Generated by Django 2.2.3 on 2019-08-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190807_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='address_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentAddressInfo'),
        ),
        migrations.AlterField(
            model_name='studentaddressinfo',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentaddressinfo',
            name='union',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Union'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentaddressinfo',
            name='upazilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Upazilla'),
            preserve_default=False,
        ),
    ]
