# Generated by Django 3.0.3 on 2020-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20200128_1231'),
        ('student', '0008_auto_20200413_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=997188, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledstudent',
            unique_together={('class_name', 'roll', 'date')},
        ),
    ]
