# Generated by Django 2.2.3 on 2019-08-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190807_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='emergency_contact_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.EmergencyContactDetails'),
        ),
    ]
