# Generated by Django 3.0.2 on 2020-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20190807_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], default=1, max_length=9),
        ),
    ]
