# Generated by Django 3.0.2 on 2020-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200109_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='status',
            field=models.CharField(choices=[('not enroll', 'Not Enroll'), ('regular', 'Regular'), ('irregular', 'Irregular')], default=1, max_length=15),
        ),
    ]
