# Generated by Django 3.0.2 on 2020-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200109_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='status',
            field=models.CharField(choices=[('not enroll', 'Not Enroll'), ('regular', 'Regular'), ('irregular', 'Irregular')], default='not enroll', max_length=15),
        ),
    ]
