# Generated by Django 3.0.2 on 2020-01-09 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200109_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
