# Generated by Django 3.0.2 on 2020-01-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_academicinfo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontactdetails',
            old_name='name',
            new_name='emergency_guardian_name',
        ),
    ]
