# Generated by Django 3.0.2 on 2020-01-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('student', '0018_auto_20200109_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddressinfo',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.District'),
        ),
        migrations.AlterField(
            model_name='studentaddressinfo',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Union'),
        ),
        migrations.AlterField(
            model_name='studentaddressinfo',
            name='upazilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Upazilla'),
        ),
    ]
