# Generated by Django 3.0.2 on 2020-01-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_classregistration'),
        ('student', '0019_auto_20200115_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassRegistration'),
        ),
    ]
