# Generated by Django 3.0.2 on 2020-01-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_classregistration'),
        ('student', '0020_auto_20200115_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='academicinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='academicinfo',
            name='roll',
        ),
    ]
