# Generated by Django 3.0.2 on 2020-01-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200116_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='date',
        ),
    ]
