# Generated by Django 3.0.2 on 2020-01-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_classregistration_name'),
        ('student', '0025_academicinfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicInfo')),
            ],
            options={
                'unique_together': {('class_name', 'student', 'roll')},
            },
        ),
    ]
