# Generated by Django 3.0.2 on 2020-01-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_enrolledstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicInfo'),
        ),
    ]
