# Generated by Django 3.0.2 on 2020-01-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20200122_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
