# Generated by Django 3.0.2 on 2020-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20200122_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=993050, unique=True),
        ),
    ]
