# Generated by Django 3.0.2 on 2020-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20200125_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=83988, unique=True),
        ),
    ]
