# Generated by Django 3.0.2 on 2020-01-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0006_classregistration_name'),
        ('student', '0034_auto_20200127_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassRegistration')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.EnrolledStudent')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
