# Generated by Django 3.1 on 2020-11-23 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_auto_20201123_1545'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=9)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.enrolledstudent')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
